### ISSUE TITLE
Review the Code of Conduct

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/lisbon#2]
We've provided a draft Code of Conduct for you that includes the contact information you provided for reporting purposes. Please ensure that these contact details are correct.

Please close this issue after all chapter organizers have reviewed the CoC thoroughly and confirmed they are comfortable enforcing it.

(This will need to be done before we can list your chapter on our website.)

**Comment by hacdias** [comment]
It looks good! 👍 Thanks!
